@Tags(['golden'])
library;

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show FontLoader;
import 'package:flutter_test/flutter_test.dart';
import 'package:summareader_sync_console/src/addresses.dart';
import 'package:summareader_sync_console/src/console_view.dart';
import 'package:summareader_sync_console/src/server.dart';
import 'package:summareader_ui/summareader_ui.dart';

/// The picture in the documentation, drawn rather than photographed.
///
/// Flutter's test binding renders the same widget tree the window shows with
/// no display involved, so this runs on a build machine and the screenshot is
/// regenerated by the same command that runs the tests:
///
///     flutter test --update-goldens --tags golden
///
/// Taken by hand it is right once and then silently wrong for every change
/// after. Tagged because a golden compares pixels, and pixels differ between
/// one machine's font rendering and another's — a CI box runs the rest of the
/// suite and leaves this one to the machine that produced it.
void main() {
  setUpAll(loadTheFonts);

  testWidgets('the documented window is what the console draws', (
    tester,
  ) async {
    // A small real install: one library, three devices that have been in use
    // for a while, and the server up — which is the only state in which the
    // dashboard button is worth showing, since that is when it is live. Three
    // devices is also what makes the third button read "Add a device", which
    // is the state a reader of the documentation is most likely to be in.
    final now = DateTime.now();
    final state = ConsoleState(
      dir: '/home/you/.config/summareader-sync',
      addr: '192.168.1.24:8099',
      running: true,
      devices: 3,
      entries: 1284,
      bytes: 13 * 1024 * 1024,
      serverBinary: '/home/you/.local/bin/summareader-sync',
      hosts: bindHosts('192.168.1.24', const [
        LanAddr('192.168.1.24', 'wlan0'),
        LanAddr('10.10.20.1', 'enp7s0'),
        LanAddr('172.17.0.1', 'docker0'),
      ]),
      atLogin: true,
      compose: true,
      paired: [
        PairedDevice(
          id: 'a',
          label: 'Workshop desktop',
          lastSeen: _minutesAgo(now, 2),
          entries: 912,
        ),
        PairedDevice(
          id: 'b',
          label: 'Pixel',
          lastSeen: _minutesAgo(now, 180),
          entries: 371,
        ),
        PairedDevice(
          id: 'c',
          label: 'Old laptop',
          revoked: true,
          lastSeen: _minutesAgo(now, 9 * 24 * 60),
          entries: 1,
        ),
      ],
    );

    tester.view.physicalSize = const Size(820, 1290);
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.reset);

    await tester.pumpWidget(
      MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: Ar.themeData(),
        home: Scaffold(
          backgroundColor: Ar.bg,
          body: ConsoleView(state: state),
        ),
      ),
    );
    await tester.pumpAndSettle();

    await expectLater(
      find.byType(ConsoleView),
      matchesGoldenFile('../../docs/desktop-window.png'),
    );
  });
}

/// The two faces the look is drawn in, loaded by hand.
///
/// A widget test renders every glyph as a filled box unless the fonts are
/// registered with the test binding — which would make this picture a diagram
/// of where the words go rather than a screenshot of the window.
Future<void> loadTheFonts() async {
  TestWidgetsFlutterBinding.ensureInitialized();
  // The icon face too, out of the SDK's own cache. Without it every icon in
  // the picture is an empty square, which reads as a bug in the window rather
  // than as an absent font in the test.
  final flutter = Platform.environment['FLUTTER_ROOT'] ?? '';
  for (final font in {
    'Caprasimo': 'assets/fonts/Caprasimo-Regular.ttf',
    'Figtree': 'assets/fonts/Figtree-Variable.ttf',
    'MaterialIcons':
        '$flutter/bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf',
  }.entries) {
    final file = File(font.value);
    if (!file.existsSync()) continue;
    final bytes = file.readAsBytesSync().buffer.asByteData();
    await (FontLoader(font.key)..addFont(Future.value(bytes))).load();
  }
}

/// A timestamp that far back, so the picture reads the way a real window does.
/// Written out as an absolute time because that is what the server sends.
String _minutesAgo(DateTime now, int minutes) =>
    now.subtract(Duration(minutes: minutes)).toUtc().toIso8601String();
