//go:build gui

package main

import (
	"image/png"
	"os"
	"path/filepath"
	"testing"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/driver/software"
	"fyne.io/fyne/v2/test"
	"fyne.io/fyne/v2/theme"
)

// The picture in the README, drawn rather than photographed.
//
// Fyne's software painter renders the same widget tree the window shows into
// an image with no display involved, so this runs on a build machine and in
// CI, and the screenshot is regenerated by the same command that runs the
// tests. Taking it by hand means it is right once and then silently wrong for
// every change after — and there is no display here to take it on anyway.
//
// The rendering is deterministic, so the file only changes when the window
// does, and `git status` after a test run is the review of that change.
func TestTheReadmeScreenshotIsWhatTheWindowDraws(t *testing.T) {
	test.NewTempApp(t)

	// A small real install: one library, three devices that have been in use
	// for a while, and the server up — which is the only state in which the
	// dashboard button is worth showing, since that is when it is live. Three
	// devices is also what makes the third button read "Add a device", which
	// is the state a reader of the README is most likely to be in.
	pane := newGUIPane(paneState{
		status:  "Running on http://192.168.1.24:8099",
		counts:  "3 devices · 1284 entries · 12.4 MB",
		dir:     "/home/you/.local/share/summareader-sync/pb_data",
		addr:    "192.168.1.24:8099",
		running: true,
		devices: 3,
		compose: true,
		paired: []overviewDevice{
			{ID: "a", Label: "Workshop desktop", LastSeen: recently(2 * time.Minute), Entries: 912},
			{ID: "b", Label: "Pixel", LastSeen: recently(3 * time.Hour), Entries: 371},
			{ID: "c", Label: "Old laptop", Revoked: true, LastSeen: recently(9 * 24 * time.Hour), Entries: 1},
		},
	})

	canvas := software.NewCanvas()
	// Twice the window's own size in pixels, because a screenshot in a README
	// is read on displays that are not the one it was drawn for.
	canvas.SetScale(2)
	canvas.SetContent(pane.content)
	canvas.Resize(fyne.NewSize(480, 640))

	if err := os.MkdirAll("docs", 0o755); err != nil {
		t.Fatal(err)
	}
	file, err := os.Create(filepath.Join("docs", "desktop-window.png"))
	if err != nil {
		t.Fatal(err)
	}
	defer file.Close()

	if err := png.Encode(file, software.RenderCanvas(canvas, theme.DefaultTheme())); err != nil {
		t.Fatal(err)
	}
}

// recently is a timestamp that far back, so the picture reads the way a real
// window does. Written out as an absolute time because that is what the
// server sends and what `ago` parses.
func recently(since time.Duration) string {
	return time.Now().Add(-since).Format(time.RFC3339)
}
